# Aggregator: includes the arrest/ framework files in dependency order.
include(joinpath(@__DIR__, "arrest", "controllers.jl"))
include(joinpath(@__DIR__, "arrest", "metrics.jl"))
include(joinpath(@__DIR__, "arrest", "bounds.jl"))
include(joinpath(@__DIR__, "arrest", "threshold.jl"))
include(joinpath(@__DIR__, "arrest", "function_controller.jl"))
include(joinpath(@__DIR__, "arrest", "composition.jl"))
include(joinpath(@__DIR__, "arrest", "arrest_model.jl"))
include(joinpath(@__DIR__, "arrest", "component.jl"))
include(joinpath(@__DIR__, "arrest", "structure.jl"))
